Stop route nesting
conveyal/gtfs-api pull request #3
Opened 2016-09-30 16:08 UTC by landonreed

@mattwigway, here's the initial work on stop -> route nesting.

- bumped pom to fix a bug with recursion
- nested route under stopType
- added additional args to filter patterns and stopTimes on `stop_id`
- added `begin_time` and `end_time` to filter patterns by dates active

**TODO:**

- determine how to pass args to sub objects

2016-09-30 22:24 UTC, mattwigway requested changes

2016-09-30 22:24 UTC, mattwigway commented on src/main/java/com/conveyal/gtfs/api/graphql/PatternFetcher.java
> +                    .filter(p -> p.entity.orderedStops.containsAll(stopIds))
Is this what we want? A pattern must contain all stopIds?

2016-09-30 22:24 UTC, mattwigway commented on src/main/java/com/conveyal/gtfs/api/graphql/RouteFetcher.java
> +        List<String> routeIds = environment.getArgument("route_id");
If you already know what routes stop at a stop, do you need to use this function?

2016-09-30 22:24 UTC, mattwigway commented on src/main/java/com/conveyal/gtfs/api/graphql/StopTimeFetcher.java
> +            // TODO stoptimes stay in correct order, right?
Remove this comment, they do.

2016-09-30 22:24 UTC, mattwigway commented on src/main/java/com/conveyal/gtfs/api/graphql/TripDataFetcher.java
> +        Long beginTime = env.getArgument("begin_time");
Do we still want begin and end time filters on trips?

2016-10-03 13:35 UTC, landonreed commented on src/main/java/com/conveyal/gtfs/api/graphql/StopTimeFetcher.java
> +            // TODO stoptimes stay in correct order, right?
done.

2016-10-03 13:39 UTC, landonreed commented on src/main/java/com/conveyal/gtfs/api/graphql/PatternFetcher.java
> +                    .filter(p -> p.entity.orderedStops.containsAll(stopIds))
Ah, maybe a more appropriate filter would be to return all patterns that match _any_ of the `stopIds`?

2016-10-03 13:42 UTC, landonreed commented on src/main/java/com/conveyal/gtfs/api/graphql/RouteFetcher.java
> +        List<String> routeIds = environment.getArgument("route_id");
I'm kind of inclined to keep it.  Even with the top-level stopTimes traversal down to routes, it seems like a useful shorthand for getting at stop-route pairs.

2016-10-03 13:50 UTC, landonreed commented on src/main/java/com/conveyal/gtfs/api/graphql/TripDataFetcher.java
> +        Long beginTime = env.getArgument("begin_time");
Perhaps not.  I could see it being useful in other cases, but we don't need it for NYSDOT atm.

2016-10-05 18:25 UTC, mattwigway requested changes
A few comments mostly around duplicate ids between feeds.

2016-10-05 18:25 UTC, mattwigway commented on src/main/java/com/conveyal/gtfs/api/graphql/PatternFetcher.java
> +                    .filter(p -> p.entity.orderedStops.containsAll(stopIds))
I think so, that's how all the other arguments work.

2016-10-05 18:25 UTC, mattwigway commented on src/main/java/com/conveyal/gtfs/api/graphql/PatternFetcher.java
> +        for (FeedSource feed : feeds) {
What happens if you have duplicate feed or pattern IDs in multiple feeds? The patterns are not nested under feeds.

2016-10-05 18:25 UTC, mattwigway commented on src/main/java/com/conveyal/gtfs/api/graphql/RouteFetcher.java
> +                .map(p -> feed.feed.routes.get(p.route_id))
You're going to wind up with duplicate routes here. Maybe after the filter do `.map(p -> p.route_id).distinct().map(feed.feed.routes::get)`

2016-10-05 18:25 UTC, mattwigway commented on src/main/java/com/conveyal/gtfs/api/graphql/StopFetcher.java
>                      Coordinate maxCoordinate = new Coordinate((Double) args.get("max_lon"), (Double) args.get("max_lat"));
Good general rule of thumb is to check if maxLon > minLon and swap them if not, same for lat.

2016-10-05 18:25 UTC, mattwigway commented on src/main/java/com/conveyal/gtfs/api/graphql/StopTimeFetcher.java
> +            if (env.getArgument("stop_id") != null) {
Does this use feed-scoped stop IDs?

2016-10-05 18:25 UTC, mattwigway commented on src/main/java/com/conveyal/gtfs/api/graphql/StopTimeFetcher.java
> +    public static List<WrappedGTFSEntity<StopTime>> apex(DataFetchingEnvironment env) {
I still feel kinda weird about having stop times at the top level of the API. Remind me the use case for this?

2016-10-05 18:25 UTC, mattwigway commented on src/main/java/com/conveyal/gtfs/api/graphql/TripDataFetcher.java
> +            if (env.getArgument("trip_id") != null) {
Same comment about duplicate trip IDs.

2016-10-05 18:31 UTC, landonreed commented on src/main/java/com/conveyal/gtfs/api/graphql/StopFetcher.java
>                      Coordinate maxCoordinate = new Coordinate((Double) args.get("max_lon"), (Double) args.get("max_lat"));
not sure that it really matters to the STRTree query though does it?

2016-10-05 18:33 UTC, landonreed commented on src/main/java/com/conveyal/gtfs/api/graphql/StopTimeFetcher.java
> +    public static List<WrappedGTFSEntity<StopTime>> apex(DataFetchingEnvironment env) {
the only reason i added patterns, stopTimes, and trips to the top level was because without referencing them directly in the root query, graphQL was throwing reference errors.  If you have ideas on how to fix that without having them at the top level, I'm all ears.

2016-10-05 18:37 UTC, landonreed commented on src/main/java/com/conveyal/gtfs/api/graphql/RouteFetcher.java
> +                .map(p -> feed.feed.routes.get(p.route_id))
👍

2016-10-05 18:42 UTC, landonreed commented on src/main/java/com/conveyal/gtfs/api/graphql/PatternFetcher.java
> +        for (FeedSource feed : feeds) {
I think for this (and the similar issues below) I just followed your lead in the StopFetcher class: https://github.com/conveyal/gtfs-api/blob/4bdb98fbf6498d4bb12a5930c7ac77489b262b17/src/main/java/com/conveyal/gtfs/api/graphql/StopFetcher.java#L41-L56

So, I guess we need to fix all of these classes...

2016-10-07 12:45 UTC, landonreed commented
OK @mattwigway, I've added TODOs for some lingering items but am merging for now so we can begin work on UI.

2016-10-07 12:49 UTC, merged